"""Figure and table emitters — the analysis -> paper-inputs layer.

Matplotlib runs head-less (``Agg``) like jansky's ``scripts/generate_figures.py``. Figures are
written as vector PDFs into ``paper/figures/``; every headline number is written to
``paper/generated/macros.tex`` as a ``\\newcommand`` so the LaTeX never hard-codes a value and the
paper regenerates from the pipeline.
"""

from __future__ import annotations

import re
from pathlib import Path

import numpy as np

from . import frbstats

__all__ = ["make_figures", "preserve_live_macros", "write_macros"]


def _fmt_p(p: float) -> str:
    """Format a p-value as a LaTeX math snippet, e.g. ``2\\times10^{-10}`` or ``0.006``."""
    if p >= 1e-3:
        return f"{p:.3f}"
    exp = int(np.floor(np.log10(p)))
    mant = p / 10**exp
    return rf"{mant:.0f}\times10^{{{exp}}}"


def _agg():
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    return plt


def make_figures(catalog: dict, stats: frbstats.BurstStats, out_dir: str | Path) -> list[Path]:
    """Write the three result figures; return their paths."""
    plt = _agg()
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    rep = np.asarray(catalog["repeater"], dtype=bool)
    paths: list[Path] = []

    # 1. Wait-time CDF with the fitted Weibull overlay.
    waits = np.sort(frbstats.wait_times(np.asarray(catalog["mjd"])[rep]))
    fig, ax = plt.subplots(figsize=(5, 3.5))
    ax.step(waits, np.arange(1, waits.size + 1) / waits.size, where="post", label="empirical")
    from scipy import stats as _st

    grid = np.linspace(waits.min(), waits.max(), 200)
    ax.plot(
        grid,
        _st.weibull_min.cdf(grid, stats.weibull.k, scale=stats.weibull.scale),
        "r--",
        label=f"Weibull k={stats.weibull.k:.2f}",
    )
    ax.set(xlabel="waiting time (days)", ylabel="CDF", title="Repeater inter-burst wait times")
    ax.legend()
    p = out / "wait_time_cdf.pdf"
    fig.tight_layout()
    fig.savefig(p)
    plt.close(fig)
    paths.append(p)

    # 2. Fluence cumulative distribution (CCDF) with the power-law slope.
    f = np.sort(np.asarray(catalog["fluence"], dtype=float))
    f = f[np.isfinite(f) & (f > 0)]
    ccdf = 1.0 - np.arange(f.size) / f.size
    fig, ax = plt.subplots(figsize=(5, 3.5))
    ax.loglog(f, ccdf, ".", ms=3, label="bursts")
    ax.set(
        xlabel="fluence (Jy ms)",
        ylabel="P(>F)",
        title=f"Fluence distribution (gamma={stats.energy.gamma:.2f})",
    )
    ax.legend()
    p = out / "fluence_ccdf.pdf"
    fig.tight_layout()
    fig.savefig(p)
    plt.close(fig)
    paths.append(p)

    # 3. DM: repeaters vs non-repeaters.
    fig, ax = plt.subplots(figsize=(5, 3.5))
    dm = np.asarray(catalog["dm"], dtype=float)
    ax.hist(dm[rep][np.isfinite(dm[rep])], bins=25, alpha=0.6, density=True, label="repeater")
    ax.hist(dm[~rep][np.isfinite(dm[~rep])], bins=25, alpha=0.6, density=True, label="non-repeater")
    ax.set(xlabel="DM (pc cm$^{-3}$)", ylabel="density", title="DM by class")
    ax.legend()
    p = out / "dm_by_class.pdf"
    fig.tight_layout()
    fig.savefig(p)
    plt.close(fig)
    paths.append(p)
    return paths


def write_macros(metrics: dict, path: str | Path) -> Path:
    """Write LaTeX ``\\newcommand`` macros for every headline number."""
    w, e, ks = metrics["weibull"], metrics["energy"], metrics["ks"]
    lines = [
        "% Auto-generated by jansky_research.report.write_macros — do not edit by hand.",
        rf"\newcommand{{\nBursts}}{{{metrics['n_bursts']}}}",
        rf"\newcommand{{\nRepeaterBursts}}{{{metrics['n_repeater_bursts']}}}",
        rf"\newcommand{{\nRepeaterSources}}{{{metrics['n_repeater_sources']}}}",
        rf"\newcommand{{\weibullK}}{{{w['k']:.2f}}}",
        rf"\newcommand{{\weibullKlo}}{{{w['k_ci_low']:.2f}}}",
        rf"\newcommand{{\weibullKhi}}{{{w['k_ci_high']:.2f}}}",
        rf"\newcommand{{\weibullNwaits}}{{{w['n_waits']}}}",
        rf"\newcommand{{\energyGamma}}{{{e['gamma']:.2f}}}",
        rf"\newcommand{{\energyGammaErr}}{{{e['gamma_err']:.2f}}}",
        rf"\newcommand{{\energyFmin}}{{{e['f_min']:.1f}}}",
        rf"\newcommand{{\energyNtail}}{{{e['n_tail']}}}",
        rf"\newcommand{{\catalogSource}}{{{metrics['source']}}}",
    ]
    # KS results + class medians for each property (so the paper hard-codes no numbers).
    names = {"width": "Width", "dm": "DM", "fluence": "Fluence"}
    # CHIME widths are in seconds; report them in ms so the paper reads naturally.
    med_scale = {"width": 1000.0}
    for key, cmd in names.items():
        if key not in ks:
            continue
        s = ks[key]
        sc = med_scale.get(key, 1.0)
        lines += [
            rf"\newcommand{{\ks{cmd}D}}{{{s['ks']:.2f}}}",
            rf"\newcommand{{\ks{cmd}P}}{{{_fmt_p(s['p'])}}}",
            rf"\newcommand{{\med{cmd}Rep}}{{{s['med_rep'] * sc:.3g}}}",
            rf"\newcommand{{\med{cmd}One}}{{{s['med_one'] * sc:.3g}}}",
        ]
    out = Path(path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n")
    return out


# --------------------------------------------------------------------------------------
# Cross-run macro preservation
# --------------------------------------------------------------------------------------

#: What a macro writer emits when a metric is absent from *this* run's metrics dict.
MACRO_PLACEHOLDER = "--"


def preserve_live_macros(new_text: str, path: str | Path) -> str:
    """Never overwrite a real macro value with a placeholder.

    Several slices run in two modes that produce **different metrics** — an offline synthetic
    validation and a real-data census; a CPU benchmark and a GPU one — and each mode's writer
    emits the *other* mode's macros as ``--`` because its own metrics dict has no such keys.
    Since both modes write the same ``generated/macros.tex``, whichever ran last silently
    blanked the other's numbers.

    That is not hypothetical. Four papers shipped abstracts citing macros that had been
    blanked this way, so their prose read as a finished claim with the number gone:

        "the detector separates type II from type III and RFI at purity --"

    and the reader has no way to tell it was ever computed. The abstracts cite *both*
    namespaces, so no single run can populate them — the file has to accumulate.

    This merges: any macro the new run would write as a placeholder keeps its existing value
    if the file on disk has a real one. A run can therefore only ever *add* information, which
    is the invariant the two-namespace design assumed and did not enforce.

    Note the asymmetry — a real value always beats a placeholder, never the reverse — so a
    genuine recomputation still overwrites, and only blanking is prevented.
    """
    path = Path(path)
    if not path.is_file():
        return new_text
    pattern = re.compile(r"\\newcommand\{\\([A-Za-z]+)\}\{(.*)\}\s*$")
    existing: dict[str, str] = {}
    for line in path.read_text(errors="ignore").splitlines():
        m = pattern.match(line.strip())
        if m and m.group(2).strip() != MACRO_PLACEHOLDER:
            existing[m.group(1)] = m.group(2)

    out = []
    for line in new_text.splitlines():
        m = pattern.match(line.strip())
        if m and m.group(2).strip() == MACRO_PLACEHOLDER and m.group(1) in existing:
            out.append(rf"\newcommand{{\{m.group(1)}}}{{{existing[m.group(1)]}}}")
        else:
            out.append(line)
    return "\n".join(out) + ("\n" if new_text.endswith("\n") else "")
