"""Figure and table emitters — the analysis -> paper-inputs layer.

Matplotlib runs head-less (``Agg``) like jansky's ``scripts/generate_figures.py``. Figures are
written as vector PDFs into ``paper/figures/``; every headline number is written to
``paper/generated/macros.tex`` as a ``\\newcommand`` so the LaTeX never hard-codes a value and the
paper regenerates from the pipeline.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import numpy as np

from . import frbstats

__all__ = [
    "make_figures",
    "preserve_live_macros",
    "preserve_live_results",
    "write_results",
    "write_macros",
]


def _fmt_p(p: float) -> str:
    """Format a p-value as a LaTeX math snippet, e.g. ``2\\times10^{-10}`` or ``0.006``."""
    if p >= 1e-3:
        return f"{p:.3f}"
    exp = int(np.floor(np.log10(p)))
    mant = p / 10**exp
    return rf"{mant:.0f}\times10^{{{exp}}}"


def _agg():
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    return plt


def make_figures(catalog: dict, stats: frbstats.BurstStats, out_dir: str | Path) -> list[Path]:
    """Write the three result figures; return their paths."""
    plt = _agg()
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    rep = np.asarray(catalog["repeater"], dtype=bool)
    paths: list[Path] = []

    # 1. Wait-time CDF with the fitted Weibull overlay. The empirical CDF must be the SAME
    # quantity the Weibull was fitted to: within-source waits. The old call used the pooled
    # wait_times, so 44 of the 61 plotted intervals crossed source boundaries -- the exact
    # quantity Methods calls meaningless -- and the figure displayed a passing fit
    # (p = 0.39 vs its own data) as a failing one (p = 1e-5 vs the wrong data).
    mjd_rep = np.asarray(catalog["mjd"])[rep]
    if "repeater_name" in catalog:
        waits = np.sort(
            frbstats.grouped_wait_times(mjd_rep, np.asarray(catalog["repeater_name"])[rep])
        )
    else:
        waits = np.sort(frbstats.wait_times(mjd_rep))
    fig, ax = plt.subplots(figsize=(5, 3.5))
    ax.step(waits, np.arange(1, waits.size + 1) / waits.size, where="post", label="empirical")
    from scipy import stats as _st

    grid = np.linspace(waits.min(), waits.max(), 200)
    ax.plot(
        grid,
        _st.weibull_min.cdf(grid, stats.weibull.k, scale=stats.weibull.scale),
        "r--",
        label=f"Weibull k={stats.weibull.k:.2f}",
    )
    ax.set(xlabel="waiting time (days)", ylabel="CDF", title="Repeater inter-burst wait times")
    ax.legend()
    p = out / "wait_time_cdf.pdf"
    fig.tight_layout()
    fig.savefig(p)
    plt.close(fig)
    paths.append(p)

    # 2. Fluence cumulative distribution (CCDF) WITH the fitted power law drawn and F_min
    # marked -- the caption promised a fit the old figure did not contain, removing from the
    # evidence the one place a reader could judge whether a single power law is adequate.
    f = np.sort(np.asarray(catalog["fluence"], dtype=float))
    f = f[np.isfinite(f) & (f > 0)]
    ccdf = 1.0 - np.arange(f.size) / f.size
    fig, ax = plt.subplots(figsize=(5, 3.5))
    ax.loglog(f, ccdf, ".", ms=3, label="bursts")
    fmin = stats.energy.f_min
    tail_frac = float(np.mean(f >= fmin))
    grid_f = np.geomspace(fmin, f.max(), 100)
    ax.loglog(
        grid_f,
        tail_frac * (grid_f / fmin) ** (-(stats.energy.gamma - 1.0)),
        "r-",
        lw=1.2,
        label=f"ML power law (gamma={stats.energy.gamma:.2f})",
    )
    ax.axvline(fmin, color="k", ls=":", lw=0.8, label=f"F_min={fmin:.1f}")
    ax.set(
        xlabel="fluence (Jy ms)",
        ylabel="P(>F)",
        title="Fluence distribution",
    )
    ax.legend(fontsize=8)
    p = out / "fluence_ccdf.pdf"
    fig.tight_layout()
    fig.savefig(p)
    plt.close(fig)
    paths.append(p)

    # 3. DM: repeaters vs non-repeaters.
    fig, ax = plt.subplots(figsize=(5, 3.5))
    dm = np.asarray(catalog["dm"], dtype=float)
    ax.hist(dm[rep][np.isfinite(dm[rep])], bins=25, alpha=0.6, density=True, label="repeater")
    ax.hist(dm[~rep][np.isfinite(dm[~rep])], bins=25, alpha=0.6, density=True, label="non-repeater")
    ax.set(xlabel="DM (pc cm$^{-3}$)", ylabel="density", title="DM by class")
    ax.legend()
    p = out / "dm_by_class.pdf"
    fig.tight_layout()
    fig.savefig(p)
    plt.close(fig)
    paths.append(p)
    return paths


def write_macros(metrics: dict, path: str | Path) -> Path:
    """Write LaTeX ``\\newcommand`` macros for every headline number."""
    w, e, ks = metrics["weibull"], metrics["energy"], metrics["ks"]
    lines = [
        "% Auto-generated by jansky_research.report.write_macros — do not edit by hand.",
        rf"\newcommand{{\nBursts}}{{{metrics['n_bursts']}}}",
        rf"\newcommand{{\nRepeaterBursts}}{{{metrics['n_repeater_bursts']}}}",
        rf"\newcommand{{\nRepeaterSources}}{{{metrics['n_repeater_sources']}}}",
        rf"\newcommand{{\weibullK}}{{{w['k']:.2f}}}",
        rf"\newcommand{{\weibullKlo}}{{{w['k_ci_low']:.2f}}}",
        rf"\newcommand{{\weibullKhi}}{{{w['k_ci_high']:.2f}}}",
        rf"\newcommand{{\weibullNwaits}}{{{w['n_waits']}}}",
        rf"\newcommand{{\energyGamma}}{{{e['gamma']:.2f}}}",
        rf"\newcommand{{\energyGammaErr}}{{{e['gamma_err']:.2f}}}",
        rf"\newcommand{{\energyFmin}}{{{e['f_min']:.1f}}}",
        rf"\newcommand{{\energyNtail}}{{{e['n_tail']}}}",
        rf"\newcommand{{\catalogSource}}{{{metrics['source']}}}",
    ]
    # round-9 additions: the honest gamma error (joint bootstrap over gamma AND f_min), the
    # Cat 1 comparand, the source-cluster Weibull CI, cadence structure, and disclosed cuts

    def _opt(name: str, value) -> str:
        return rf"\newcommand{{\{name}}}{{{'--' if value is None else value}}}"

    eb = metrics.get("energy_bootstrap") or {}
    kci = metrics.get("weibull_k_cluster_ci") or [None, None]
    lines += [
        _opt("energyGammaBootErr", eb.get("gamma_boot_sd")),
        _opt("energyGammaCIlo", eb.get("gamma_ci_low")),
        _opt("energyGammaCIhi", eb.get("gamma_ci_high")),
        _opt("energyFminCIlo", eb.get("f_min_ci_low")),
        _opt("energyFminCIhi", eb.get("f_min_ci_high")),
        _opt("energyGammaRef", metrics.get("gamma_ref")),
        _opt("energyGammaRefErr", metrics.get("gamma_ref_err")),
        _opt("energyGammaAgree", metrics.get("gamma_agreement_sigma")),
        _opt("energyGammaNoExcl", metrics.get("gamma_without_excluded")),
        _opt("nExcludedFlag", metrics.get("n_excluded_flag")),
        _opt("weibullKcluLo", kci[0]),
        _opt("weibullKcluHi", kci[1]),
        _opt("nWaitSources", metrics.get("n_wait_sources")),
        _opt("nWaitsSameTransit", metrics.get("n_waits_same_transit")),
        _opt("nWaitsSidereal", metrics.get("n_waits_sidereal_day")),
        _opt("nWidthLimitsOne", metrics.get("n_width_limits_one")),
        _opt("nWidthLimitsRep", metrics.get("n_width_limits_rep")),
    ]
    kss = metrics.get("ks_source_level") or {}
    for key, cmd in (("width", "Width"), ("dm", "DM"), ("fluence", "Fluence")):
        s = kss.get(key)
        lines += [
            _opt(f"ks{cmd}DSrc", None if s is None else f"{s['ks']:.2f}"),
            _opt(f"ks{cmd}PSrc", None if s is None else _fmt_p(s["p"])),
            _opt(f"ks{cmd}NSrc", None if s is None else int(s["n_rep_sources"])),
        ]
    # KS results + class medians for each property (so the paper hard-codes no numbers).
    names = {"width": "Width", "dm": "DM", "fluence": "Fluence"}
    # CHIME widths are in seconds; report them in ms so the paper reads naturally.
    med_scale = {"width": 1000.0}
    for key, cmd in names.items():
        if key not in ks:
            continue
        s = ks[key]
        sc = med_scale.get(key, 1.0)
        lines += [
            rf"\newcommand{{\ks{cmd}D}}{{{s['ks']:.2f}}}",
            rf"\newcommand{{\ks{cmd}P}}{{{_fmt_p(s['p'])}}}",
            rf"\newcommand{{\med{cmd}Rep}}{{{s['med_rep'] * sc:.3g}}}",
            rf"\newcommand{{\med{cmd}One}}{{{s['med_one'] * sc:.3g}}}",
        ]
    out = Path(path)
    out.parent.mkdir(parents=True, exist_ok=True)
    # Merge rather than overwrite (the CLAUDE.md invariant this writer was missing): the
    # \catalogSource marker lets preserve_live_macros refuse a synthetic run overwriting the
    # real values -- previously a silent synthetic fallback could rewrite this file while
    # results/metrics.json was correctly preserved and every guard stayed green.
    out.write_text(preserve_live_macros("\n".join(lines) + "\n", out))
    return out


# --------------------------------------------------------------------------------------
# Cross-run macro preservation
# --------------------------------------------------------------------------------------

#: What a macro writer emits when a metric is absent from *this* run's metrics dict.
MACRO_PLACEHOLDER = "--"


def preserve_live_macros(new_text: str, path: str | Path) -> str:
    """Never overwrite a real macro value with a placeholder.

    Several slices run in two modes that produce **different metrics** — an offline synthetic
    validation and a real-data census; a CPU benchmark and a GPU one — and each mode's writer
    emits the *other* mode's macros as ``--`` because its own metrics dict has no such keys.
    Since both modes write the same ``generated/macros.tex``, whichever ran last silently
    blanked the other's numbers.

    That is not hypothetical. Four papers shipped abstracts citing macros that had been
    blanked this way, so their prose read as a finished claim with the number gone:

        "the detector separates type II from type III and RFI at purity --"

    and the reader has no way to tell it was ever computed. The abstracts cite *both*
    namespaces, so no single run can populate them — the file has to accumulate.

    This merges: any macro the new run would write as a placeholder keeps its existing value
    if the file on disk has a real one. A run can therefore only ever *add* information, which
    is the invariant the two-namespace design assumed and did not enforce.

    Note the asymmetry — a real value always beats a placeholder, never the reverse — so a
    genuine recomputation still overwrites, and only blanking is prevented.
    """
    path = Path(path)
    if not path.is_file():
        return new_text
    pattern = re.compile(r"\\newcommand\{\\([A-Za-z]+)\}\{(.*)\}\s*$")
    existing: dict[str, str] = {}
    for line in path.read_text(errors="ignore").splitlines():
        m = pattern.match(line.strip())
        if m and m.group(2).strip() != MACRO_PLACEHOLDER:
            existing[m.group(1)] = m.group(2)

    # A synthetic run must not overwrite a real value even when both are "real values" to the
    # placeholder rule above. That case is NOT hypothetical and is not rare: an audit of every
    # slice (scripts/audit_macro_namespaces.py) found 34 of 42 carrying at least one macro whose
    # name means different things in the two run modes, about twenty of them numeric --
    # \hiVflat 257 -> 231, \rmRatio 5.4 -> 8.4, \vlassNconfirmed 2 -> 0. Namespacing each one
    # is the clean fix and remains worth doing for clarity; this stops the bleeding for all of
    # them at once, using the provenance the macro files already carry.
    downgrade = _macros_are_synthetic(new_text, pattern) and not _macros_are_synthetic(
        path.read_text(errors="ignore"), pattern
    )

    out = []
    for line in new_text.splitlines():
        m = pattern.match(line.strip())
        if not m:
            out.append(line)
            continue
        name, value = m.group(1), m.group(2)
        keep = name in existing and (value.strip() == MACRO_PLACEHOLDER or downgrade)
        out.append(rf"\newcommand{{\{name}}}{{{existing[name]}}}" if keep else line)
    return "\n".join(out) + ("\n" if new_text.endswith("\n") else "")


def _macros_are_synthetic(text: str, pattern: re.Pattern[str]) -> bool:
    r"""Whether a macro block was written by a synthetic run, per its own ``*Source`` macro.

    Every slice emits one (``\hiSource``, ``\ptSource``, ``\catalogSource`` ...), and the
    offline leg writes a value naming itself synthetic. That is the only provenance a macro
    file carries, and it is enough to tell a rebuild from a downgrade.
    """
    for line in text.splitlines():
        m = pattern.match(line.strip())
        if m and m.group(1).lower().endswith("source"):
            low = m.group(2).lower()
            # Match _results_are_real's rule: a MIXED source that names both legs (torchfdmt's
            # is "synthetic injection (unprefixed keys) + Parkes/UWL ... (real ...)") counts as
            # REAL. The naive `"synthetic" in low` treated every real torchfdmt rerun as a
            # synthetic downgrade and silently discarded its macro updates -- caught 2026-08-25
            # when a fresh single-invocation benchmark left \spBruteSpeedup at the spliced 29.
            return "synthetic" in low and "real" not in low
    return False


# --------------------------------------------------------------------------------------
# The results-JSON counterpart of preserve_live_macros.
# --------------------------------------------------------------------------------------

RESULTS_MERGE_KEY = "_merge"


def _results_are_real(d: dict) -> bool:
    """Whether a metrics dict describes real data.

    Deliberately the same test ``scripts/guard_real_results.py`` applies at packaging time: a
    ``source`` that does not name itself synthetic. Keying only on ``is_real`` was not enough --
    most slices never set it, so a first cut of this guard silently protected 3 files out of 25.
    """
    if d.get("is_real") is True:
        return True
    if d.get("is_real") is False:
        return False
    src = d.get("source")
    if not isinstance(src, str) or not src:
        return False  # no provenance marker at all: nothing to protect, and nothing claimed
    low = src.lower()
    # A MIXED source names both legs -- stokesv_discovery's is "synthetic recover-a-known +
    # real RACS-mid epoch pair", and it is allowlisted in guard_real_results precisely because
    # the real census is in there. Treating any mention of "synthetic" as synthetic would have
    # left that file overwritable by its own offline rebuild.
    return "synthetic" not in low or "real" in low


def preserve_live_results(new: dict, path: str | Path) -> dict:
    """Return the metrics dict to write, so that a results file only ever gains information.

    ``preserve_live_macros`` fixed this for ``generated/macros.tex`` and the results JSON was
    left with the same hole, which has now bitten three separate slices:

    - ``typeii``: ``run(".", offline=True)`` replaced the real census with synthetic output,
      deleting 3429 lines and flipping ``is_real`` True -> False. ``make guard-real`` caught it
      only at packaging time, which is late.
    - ``southern``: an offline rebuild would have written the synthetic field's counts over
      1545 real matches.
    - ``torchfdmt``: a CPU-only re-run drops the GPU benchmark columns, so the committed row
      was assembled by hand-patching them back in -- producing a row no single invocation
      could have produced, with no record that it was a splice.

    The rule is the macros rule, applied to structured data: **a run may only add information,
    and a real result is never replaced by a synthetic one.** Concretely:

    1. Nothing on disk: write the new payload.
    2. On disk but not real: the new payload wins. A real run must be able to replace a
       synthetic placeholder, and synthetic-over-synthetic is a plain rebuild.
    3. On disk real, new payload real: merge. The new run's values win for every key it
       carries, and keys only the previous run produced are retained -- this is what stops a
       CPU-only benchmark re-run from silently dropping a real GPU column. Retained keys are
       listed under ``_merge`` so the file cannot look like a single invocation when it is not.
    4. On disk real, new payload **not** real: keep the file as it stands. This is the clobber,
       and refusing it is the whole point; the synthetic numbers still reach the paper through
       the ``Syn``-namespaced macros, which ``preserve_live_macros`` merges separately.

    Case 4 is why ``make figures`` is safe to run in the repo root even though every offline
    slice is invoked there with ``--out .``.
    """
    path = Path(path)
    if not path.is_file():
        return new
    try:
        old = json.loads(path.read_text())
    except (json.JSONDecodeError, OSError, UnicodeDecodeError):  # unreadable: allow a write
        return new
    if not isinstance(old, dict) or not _results_are_real(old):
        return new
    if not _results_are_real(new):
        # A synthetic run must not overwrite real evidence, in place, in the repo root.
        return old

    merged = {**old, **new}
    retained = sorted(k for k in old if k not in new and not k.startswith("_"))
    if retained:
        merged[RESULTS_MERGE_KEY] = {
            "retained_from_previous_run": retained,
            "note": (
                "These keys are not from the run that wrote the rest of this file. They were "
                "carried over so a partial re-run could not delete them; treat any comparison "
                "spanning them as cross-run."
            ),
        }
    else:
        merged.pop(RESULTS_MERGE_KEY, None)
    return merged


def write_results(new: dict, path: str | Path) -> dict:
    """Merge via :func:`preserve_live_results` and write the result. Returns what was written."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = preserve_live_results(new, path)
    text = json.dumps(payload, indent=2) + "\n"
    if path.is_file():
        try:
            if json.loads(path.read_text()) == payload:
                return payload  # unchanged: leave the committed bytes alone
        except (json.JSONDecodeError, OSError, UnicodeDecodeError):
            pass
    path.write_text(text)
    return payload
